- hosts: node_amd64
  roles:
    - common
    - common-node
    - cross-compilers
    - compilers
    - babeltrace
    - binutils-gdb
    - liburcu
    - lttng-ust
    - lttng-tools
    - lttng-modules
    - lttng-analyses
    - libs-i386
