- hosts: node-amd64
  roles:
    - common
    - cross-compilers
    - compilers
    - babeltrace
    - liburcu
    - lttng-ust
    - lttng-tools
    - lttng-modules
    - lttng-analyses
    - lttng-scope
