---
compilers_packages:
  - gcc
  - gcc-11
  - gcc-12
  - gcc-13
  - gcc-14
  - g++
  - g++-11
  - g++-12
  - g++-13
  - g++-14
  - clang
  - clang-15
  - clang-16
  - clang-17
  - libclang-dev
  - libclang-15-dev
  - libclang-16-dev
  - libclang-17-dev
  - clang-format
  - clang-format-15
  - clang-format-16
  - clang-format-17
  - clang-tidy
  - clang-tidy-15
  - clang-tidy-16
  - clang-tidy-17
  - bear
