---
__common_packages:
  - openssh-server
  - sudo
  - default-jdk-headless
  - git
  - vim
  - emacs-nox
  - tree
  - htop
  - build-essential
  - clang
  - clang-tools
  - automake
  - autoconf
  - libtool
  - bison
  - flex
  - libtap-harness-archive-perl
  - jq
  - cppcheck
  - cloc
  - python-virtualenv
  - curl
  - gettext
  - libssl-dev
  - psmisc
  - rsync
  - pbzip2
