---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure lttng-analyses build dependencies are installed.
  apt: "name={{ item }} state=present"
  with_items: "{{ lttng_analyses_packages }}"

