---
common_node_patterns:
  - base
  - devel_basis

common_node_packages:
  - autoconf
  - automake
  - bison
  - curl
  - flex
  - gettext-runtime
  - git-core
  - java-1_8_0-openjdk-devel
  - java-1_8_0-openjdk-headless
  - java-11-openjdk-devel
  - java-11-openjdk-headless
  - jq
  - libopenssl-devel
#  - libtap-harness-archive-perl
  - libtool
  - maven
  - openssh
  - psmisc
#  - python-virtualenv
  - rsync
  - sudo
#  - tree
  - vim

common_node_products:
  # Required for sle-module-legacy
  - sle-module-server-applications
  # For java 1.8
  - sle-module-legacy
